# Generated by Django 5.1.dev20231215200100 on 2023-12-17 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="owner",
            new_name="user",
        ),
    ]
