# Generated by Django 5.1.dev20231215200100 on 2023-12-17 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_body_comment_text_rename_owner_comment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created",
            new_name="created_at",
        ),
    ]
